services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    env_file:
      - .env
    volumes:
      - ${CONFIG_PATH}:/config
      - ${BLACKHOLE_PATH}:/downloads
    restart: unless-stopped
    network_mode: "container:gluetun"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    env_file:
      - .env
    network_mode: "container:gluetun"
    restart: unless-stopped
